title: Discover PERL Mortgage
email: runderwood@perlmortgage.com
author: Ryan Underwood
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed



collections:
  careers:
    output: true
    permalink: /:collection/:permalink
  stories:
    output: true
    permalink: /:permalink
  leadership:
    output: true
    permalink: /:permalink










# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
