title: Discover PERL Mortgage
email: runderwood@perlmortgage.com
author: Ryan Underwood
description: 'PERL Mortgage is proud to serve communities in more than 30 states from coast to coast, and we look forward to continued national growth. Funding more than $1 billion in mortgage loans, PERL is consistently ranked as a Top 100 Mortgage Lender in the country by Mortgage Executive Magazine and Scotsman Guide.'
keywords: 'Chicago, Mortgage, Lender, Recruiting, Real Estate, Broker, Homebuyer, Home, House, About PERL Mortgage, PERL, Your Lender for Life, Ken Perlmutter, Ryan Underwood'
nmls: 'NMLS #19186'
featured_image: '/uploads/perl_recruit_home.jpg'
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


collections:
  careers:
    output: true
    permalink: /:collection/:permalink
  stories:
    output: true
    permalink: /:permalink
  leadership:
    output: true
    permalink: /:permalink










# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
